fix GCC compilation issue when CCI_ENABLE_CONTRACTS is not set
GCC gave the following error:

    ../include/cci/util/contracts.hpp:51:39: error: missing binary operator before token "("
     #if defined(__GNUC__) || __has_builtin(__builtin_unreachable)
                                           ^

This change fixes that, by defining __has_builtin
for compilers that don't provide it.

Also, fixed cci_unreachable(cond) => cci_unreachable().

And simplify the condition:

    #if defined(__GNUC__) || defined(__clang__)

by:

    #if defined(__GNUC__) || defined(__clang__)

The reason being that Clang defines __GNUC__.