Fix wrong `missing "/' character` error.
This code:

    "test"

Would give this error:

    test.c:1:1: error: missing terminating " character
    "test"
    ^

Now fixed.